-- 0.5: executar UMA VEZ em homologacao, depois de exportar dados e metadados.
-- DDL Oracle faz commit implicito. Nao executar novamente em caso de sucesso parcial.
-- Nao remove dados nem altera o modulo ORDS antigo.
ALTER TABLE pessoa ADD (
    char_diagnostico VARCHAR2(2000 BYTE),
    char_tratamento VARCHAR2(2000 BYTE),
    char_medicamento VARCHAR2(2000 BYTE),
    char_alergia VARCHAR2(2000 BYTE),
    char_observacoes VARCHAR2(2000 BYTE),
    data_obito DATE,
    num_frequencia_cesta NUMBER(3),
    CONSTRAINT ck_pessoa_cesta CHECK (num_frequencia_cesta BETWEEN 1 AND 365),
    CONSTRAINT ck_pessoa_obito CHECK
        (data_obito IS NULL OR (data_obito >= data_nascimento AND status = 'INATIVO'))
);

CREATE TABLE entrega_cesta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id NUMBER NOT NULL,
    data_entrega DATE NOT NULL,
    frequencia_dias NUMBER(3) NOT NULL,
    registrado_em TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_cesta_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa(id),
    CONSTRAINT uq_cesta_dia UNIQUE (pessoa_id, data_entrega),
    CONSTRAINT ck_cesta_dia CHECK (data_entrega = TRUNC(data_entrega)),
    CONSTRAINT ck_cesta_freq CHECK (frequencia_dias BETWEEN 1 AND 365)
);

-- Nao existe coluna editavel de ultima entrega: a API consulta MAX no historico.
-- Nao ha entrega retroativa, exclusao ou alteracao do historico nesta versao.
