
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_GESTAORCC  Date: Sat Sep 26 11:56:05 2026
--

DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'gestaorcc',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'gestao_rcc',
      p_base_path      => '/rcc/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN
    INSERT INTO pessoa (
        nome,
        cpf,
        data_nascimento,
        telefone,
        endereco,
        status
    ) VALUES (
        :nome,
        :cpf,
        TO_DATE(:data_nascimento, ''YYYY-MM-DD''),
        :telefone,
        :endereco,
        NVL(:status, ''ATIVO'')
    ) RETURNING id INTO :id;

    :status_code := 201; -- Created
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'SELECT
    id,
    nome,
    cpf,
    TO_CHAR(data_nascimento, ''YYYY-MM-DD'') AS data_nascimento,
    telefone,
    endereco,
    status
FROM pessoa
ORDER BY nome ASC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'SELECT
    id,
    nome,
    cpf,
    TO_CHAR(data_nascimento, ''YYYY-MM-DD'') AS data_nascimento,
    telefone,
    endereco,
    status
FROM pessoa
WHERE id = :id;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN
    UPDATE pessoa
    SET nome            = :nome,
        cpf             = :cpf,
        data_nascimento = TO_DATE(:data_nascimento, ''YYYY-MM-DD''),
        telefone        = :telefone,
        endereco        = :endereco,
        status          = :status
    WHERE id = :id;

    :status_code := 200; -- OK
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gestao_rcc',
      p_pattern        => 'pessoas/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>
'BEGIN
    DELETE FROM pessoa
    WHERE id = :id;

    :status_code := 200; -- OK
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 400;
END;');

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;
