-- Estrutura lógica lida de DBMS_METADATA em 26/09/2026.
-- Versão portável: omitidos schema, tablespace e parâmetros físicos do APEX.
-- SOMENTE para um schema de demonstração vazio. Não executar no banco existente.
-- Não contém dados. A restauração deste script em outro schema ainda não foi testada.
CREATE TABLE pessoa (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    cpf VARCHAR2(14) UNIQUE,
    data_nascimento DATE,
    telefone VARCHAR2(20),
    endereco VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'ATIVO',
    data_cadastro TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servico_prestado (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id NUMBER NOT NULL,
    tipo_servico VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    data_servico DATE DEFAULT SYSDATE,
    CONSTRAINT fk_servico_pessoa FOREIGN KEY (pessoa_id)
        REFERENCES pessoa(id) ON DELETE CASCADE
);
